
export const ADD_FAV = "ADD_FAV"

export const REMOVE_FAV = "REMOVE_FAV"

export const DOWNLOAD = "DOWNLOAD"

export const FAV_PREVIEW = "FAV_PREVIEW"

export const FETCH_PHOTO = "FETCH_PHOTO"

export const FETCH_PHOTO_BEGIN = "FETCH_PHOTO_BEGIN"

export const FETCH_PHOTO_SUCCESS = "FETCH_PHOTO_SUCCESS"

export const FETCH_PHOTO_FAILURE = "FETCH_PHOTO_FAILURE"
 
